# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 566ea13672af8c827e82783f0705ea98423bcdd842adf981e409d51c91591b36d4cbef5e433e2b57a31730527e789a64195f4904fae03895c6fc29cda0e9e66e

test:
  secret_key_base: e9f711b236da2127f7e5fe4839137c05137507ac895a577969a9c0fe83d29c65aded7b22dd6f61fe87e26efd2353c83410a739ae00a2d05044ff8d39068fadef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
